# Generated by Django 5.2.9 on 2025-12-23 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('is_signed_in', models.BooleanField(default=True)),
            ],
        ),
    ]
